### PR TITLE
Unittests

### PR DESCRIPTION
**Pull request by lbreede**
Added python unittests to checks the integrity of the cameras.json file.
Checks for:
- Uniqueness of camera names, sensor sizes per camera etc..
- Checks that sensor sizes are lists with exactly two numbers
- Checks for correct value types (descriptions are strings, tags are lists etc..)

### CODE REVIEW

**Comment by AntonPalmqvist** [comment]
Just out of curiosity, how are you using this in practice? Is this for a studio pipeline?

**Comment by lbreede** [comment]
First of all, feel free to entirely throw this out the window haha.
Basically, you can use GitHub Actions to have custom code run for every push and pull request.
You can then write unittests that check basic things like "do we have duplicate cameras", "does the Alexa have duplicate sensor sizes", "is the list of cameras in order" etc..
It's just a quick indication of errors before a human looks over it.

**Comment by AntonPalmqvist** [comment]
It's definitely interesting, and I'm meaning to look into using GitHub Actions at some point.
I really appreciate your effort here. Let me have a think about the needs for this project!

**Comment by lbreede** [comment]
As is said, this is probably not necessary at this point. It's a nice way to enforce some style guidelines and required fields. I also don't want to be too assertive, I just really love the project and always wanted to contribute to a repo I'm passionate about.

**Comment by AntonPalmqvist** [comment]
I really appreciate the support. It's people like you who makes projects like these even better!

**Pull request closed without merging**
